version: '{build}'
environment:
  matrix:
  - GENERATOR: "MSYS Makefiles"
    ARCH: i686 # this is for 32-bit MinGW-w64
  - GENERATOR: "MSYS Makefiles"
    ARCH: 64
cache:
  - i686-4.9.2-release-win32-sjlj-rt_v3-rev1.7z
  - x86_64-4.9.2-release-win32-seh-rt_v3-rev1.7z
  - libusb-1.0.20.7z
build_script:
- ps: |
    mkdir build
    cd build
    if ($env:GENERATOR -ne "MSYS Makefiles") {
      cmake .. -G"$env:GENERATOR"
      cmake --build . --config Debug
    }
- cmd: |
    if "%GENERATOR%"=="MSYS Makefiles" (C:\MinGW\msys\1.0\bin\sh --login /c/projects/stlink/scripts/appveyor-mingw.sh)
