#ifndef STLINK_VERSION_H_
#define STLINK_VERSION_H_

#define STLINK_VERSION       "@PROJECT_VERSION@"
#define STLINK_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define STLINK_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define STLINK_VERSION_PATCH @PROJECT_VERSION_PATCH@

#endif /* STLINK_VERSION_ */
