#ifndef VERSION_H
#define VERSION_H

#define STLINK_VERSION       "@PROJECT_VERSION@"
#define STLINK_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define STLINK_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define STLINK_VERSION_PATCH @PROJECT_VERSION_PATCH@

#endif // VERSION_H
